name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: "npm"

      - run: npm install --frozen-lockfile

      # Biome
      - uses: biomejs/setup-biome@v2
      - run: biome ci .

      # Build
      - run: npm run build

      # Tests + coverage
      - run: npm run test

      # Upload coverage for badge/commenting
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
